name: listme
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  confetti: ^0.7.0
  cupertino_icons: ^1.0.5 # hay una dependecia quelo usa, no borrar
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  go_router: ^10.0.0
  google_mobile_ads: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  implicitly_animated_reorderable_list_2: ^0.5.1
  intl: ^0.18.1
  page_view_dot_indicator: ^2.3.0
  percent_indicator: ^4.2.3
  share_plus: ^7.1.0
  url_launcher: ^6.1.12
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - env/
    - assets/
    - assets/svg/
    - assets/splash/

flutter_native_splash:
  color: "#00BCD4"
  image: assets/splash/splash.png
  image_dark: assets/splash/splash.png
  android_12:
    image: assets/splash/splash.png
    icon_background_color: "#00BCD4"
    image_dark: assets/splash/splash.png
    icon_background_color_dark: "#00BCD4"
  web: false
