name: listme
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  confetti: ^0.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.7
  go_router: ^10.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  implicitly_animated_reorderable_list_2: ^0.5.1
  intl: ^0.18.1
  page_view_dot_indicator: ^2.3.0
  percent_indicator: ^4.2.3
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - env/
    - assets/
    - assets/svg/
